---
# Backup 

- name: "Backup | Installing system dependencies"
  apt:
    pkg:
      - python-pip
      - gpg

- name: "Backup | Installing python dependencies"
  pip:
    name: boto3

- name: "Backup | Ensure that the backup directory exists"
  file:
    path: "/data/backups/"
    state: directory

- name: "Backup | Execute backup script"
  shell: "{{ backup_script }}"
  register: backup_exec
  when: backup_script is defined

- name: "Backup | List output"
  debug: var=backup_exec.stdout_lines
  when: backup_script is defined

- name: "Backup | List files to backup"
  shell: ls -lhR /data/backups/
  register: targets

- include_tasks: backup.yml
  loop: "{{ targets.stdout_lines }}"

- name: "Backup | Cleaning up the backup directory"
  block:
  - name: "Backup | Collect a list of all files to clean up"
    find:
      paths: "/data/backups/"
      hidden: True
      recurse: True
    register: collected_files

  - name: "Backup | Collect a list of all directories to clean up"
    find:
      paths: "/data/backups/"
      hidden: True
      recurse: True
      file_type: directory
    register: collected_directories

  - name: "Backup | Clean up old backups"
    file:
      path: "{{ item.path }}"
      state: absent
    with_items: >
      {{
        collected_files.files
        + collected_directories.files
      }}
